version: '3.5'

services:
    srapp.sitrickdev.com:
        container_name: app
        environment:
            DB_HOST: mysql.sitrickdev.com
            DB_USERNAME: srapp
            DB_PASSWORD: test
            DB_DATABASE: srapp
            APP_NAME: "SportsRecruits Code Test"
            APP_ENV: local
            APP_DEBUG: 1
            APP_URL: "http://localhost:8001"
            XDEBUG_CONFIG: remote_host=host.docker.internal
        ports:
            - "8001:8001"
        volumes:
            - ./project:/var/www/html
        build: .
        command: bash -c "composer install && php -S app:8001 -t public"
        restart: always

    mysql.sitrickdev.com:
        container_name: mysql
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: srapp
            MYSQL_USER: srapp
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        command: mysqld --default-authentication-plugin=mysql_native_password
        ports:
            - "3322:3306"
        volumes:
            - "~/.srapp/mysql:/var/lib/mysql"

    mysql-test.sitrickdev.com:
        container_name: mysql-test
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: srapp
            MYSQL_USER: srapp
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        command: mysqld --default-authentication-plugin=mysql_native_password
        ports:
            - "3323:3306"
        volumes:
            - "~/.srapp/mysql-test:/var/lib/mysql"

    redis.sitrickdev.com:
        container_name: redis
        image: redis:6.2
